export const drivers = [
  "Verstappen",
  "Norris",
  "Leclerc",
  "Piastri",
  "Sainz",
  "Russell",
  "Hamilton",
  "Alonso",
  "Gasly",
  "Hulkenberg",
  "Tsunoda",
  "Stroll",
  "Ocon",
  "Albon",
  "Bearman",
  "Antonelli",
  "Lawson",
  "Doohan",
  "Bortoleto",
  "Hadjar",
];

export const teamColors = {
  Mercedes: "#00D2BE",
  "Red Bull": "#0600EF",
  Ferrari: "#DC0000",
  McLaren: "#FF8700",
  "Aston Martin": "#006F62",
  Alpine: "#0090FF",
  Sauber: "#C00000",
  "Racing Bulls": "#2B4562",
  Williams: "#005AFF",
  Haas: "#E6002B",
};

export const driverTeams = {
  Hamilton: "Ferrari",
  Russell: "Mercedes",
  Verstappen: "Red Bull",
  Hadjar: "Racing Bulls",
  Leclerc: "Ferrari",
  Norris: "McLaren",
  Piastri: "McLaren",
  Alonso: "Aston Martin",
  Stroll: "Aston Martin",
  Ocon: "Haas",
  Gasly: "Alpine",
  Sainz: "Williams",
  Antonelli: "Mercedes",
  Tsunoda: "Racing Bulls",
  Lawson: "Red Bull",
  Albon: "Williams",
  Bearman: "Haas",
  Hulkenberg: "Sauber",
  Doohan: "Alpine",
  Bortoleto: "Sauber",
};

export const races = [
  "Australia",
  "China Sprint",
  "China",
  "Japan",
  "Bahrain",
  "Saudi Arabia",
  "Miami Sprint",
  "Miami",
  "Imola",
  "Monaco",
  "Canada",
  "Spain",
  "Austria",
  "United Kingdom",
  "Hungary",
  "Belgium Sprint",
  "Belgium",
  "Netherlands",
  "Italy",
  "Azerbaijan",
  "Singapore",
  "Austin Sprint",
  "Austin",
  "Mexico",
  "Sao Paulo Sprint",
  "Sao Paulo",
  "Las Vegas",
  "Qatar Sprint",
  "Qatar",
  "Abu Dhabi",
];

export const pointsMap = {
  1: 25,
  2: 18,
  3: 15,
  4: 12,
  5: 10,
  6: 8,
  7: 6,
  8: 4,
  9: 2,
  10: 1,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
};

export const sprintPointsMap = {
  1: 8,
  2: 7,
  3: 6,
  4: 5,
  5: 4,
  6: 3,
  7: 2,
  8: 1,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
};

// Past race results for the 2025 season
export const pastRaceResults = {
  "Australia": [
    "Norris",
    "Verstappen",
    "Russell",
    "Antonelli",
    "Albon",
    "Stroll",
    "Hulkenberg",
    "Leclerc",
    "Piastri",
    "Hamilton",
    "Gasly",
    "Tsunoda",
    "Ocon",
    "Bearman",
    "Lawson",
    "Bortoleto",
    "Alonso",
    "Sainz",
    "Doohan",
    "Hadjar"
  ],
  "China Sprint": [
    "Hamilton",
    "Piastri",
    "Verstappen",
    "Russell",
    "Leclerc",
    "Tsunoda",
    "Antonelli",
    "Norris",
    "Stroll",
    "Alonso",
    "Albon",
    "Gasly",
    "Hadjar",
    "Lawson",
    "Bearman",
    "Ocon",
    "Sainz",
    "Bortoleto",
    "Hulkenberg",
    "Doohan"
  ],
  "China": [
    "Piastri",
    "Norris",
    "Russell",
    "Verstappen",
    "Ocon",
    "Antonelli",
    "Albon",
    "Bearman",
    "Stroll",
    "Sainz",
    "Hadjar",
    "Lawson",
    "Doohan",
    "Bortoleto",
    "Hulkenberg",
    "Tsunoda",
    "Alonso",
    "Leclerc",
    "Gasly",
    "Hamilton"
  ]
};
